name: crypt
version: 3.0.1
description: One-way string hashing for salted passwords using the Unix crypt format
homepage: https://github.com/hoylen/dart-crypt
environment:
  sdk: ">=2.3.0 <3.0.0"
dev_dependencies:
  test: ">=0.12.10 <1.13.0"
dependencies:
  crypto: "^2.1.4"
